# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Musings of a Software Developer
email: Chris@ChrisIrvine.co.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chrisirvine.co.uk" # the base hostname & protocol for your site
twitter_username: ctdirvine
github_username:  christdi

# Build settings
markdown: kramdown
